# Site settings
title: 0x27 Finger Discount
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The adventures and exploits of a student/developer as they explore
  wonderous new lands of unsanitized inputs, programming languages, 
  and Computer Science 3.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://0x27.me" # the base hostname & protocol for your site
twitter_username: info_dox
github_username:  '0x27'
exclude: PoC||GTFO

# Build settings
markdown: kramdown
kramdown:
  input: GFM
